#version: "3.9"

services:
  php:
    image: php:8.2-fpm-alpine
    container_name: php-fpm
    volumes:
      - ./app:/var/www/html
    networks:
      - backend

  db:
    image: postgres:16-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypass
      POSTGRES_DB: myapp
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

volumes:
  pgdata:  # persistent volume for PostgreSQL

networks:
  backend:
    driver: bridge
