# version: '3'

services:
  gitlab:
    build:
      context: ./docker/
    container_name: my-gitlab-container
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
    volumes:
      - ./gitlab/config:/etc/gitlab
      - ./gitlab/logs:/var/log/gitlab
      - ./gitlab/data:/var/opt/gitlab
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://localhost'
        gitlab_rails['db_adapter'] = 'postgresql'
        gitlab_rails['db_encoding'] = 'unicode'
        gitlab_rails['db_database'] = 'gitlabhq_production'
        gitlab_rails['db_pool'] = 10
        gitlab_rails['db_username'] = 'gitlab'
        gitlab_rails['db_password'] = 'your_password'
        gitlab_rails['db_host'] = 'your_db_host'
        gitlab_rails['db_port'] = 5432
    restart: always
